spring:
  redis:
    uri: redis://default:FAZRIEmnCIwKxdvC5aFN3YXNAqL4UAGQ@redis-12184.c11.us-east-1-2.ec2.redns.redis-cloud.com:12184
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: journaldb
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /journal

